### ISSUE TITLE
Задача о траекториях кузнечика

### ISSUE THREAD

**Issue by pikvic** [fefupyjava/algodspy#34]
### Задача
Необходимо реализовать алгоритм решения задачи о [траекториях кузнечика](https://foxford.ru/wiki/informatika/odnomernoe-dinamicheskoe-programmirovanie-kolichestvo-sposobov), оформив его в виде отдельного класса с методом run. При этом в конструкторе класса (методе __init__) должен быть опциональный параметр k - максимальный шаг кузнечика. То есть при k = 3 кузнечик сможет прыгать на 1, 2 или 3 клетки вперёд. По умолчанию k=2.
 
### Детали
Класс должен содержать метод run, принимающий в качестве параметров:
- n - число, определяющее номер клетки, до которой нужно посчитать траектории
- kind='naive' - опциональный аргумент, указывающий на тип реализации алгоритма, возможные значения которого 'naive' - наивный алгоритм, 'recursive' - рекурсивный алгоритм сверху-вниз, 'memoized' - рекурсивный алгоритм с [мемоизацией](https://en.wikipedia.org/wiki/Memoization), 'dynamic' - в стиле динамического программирования снизу-вверх.

Результат метода - количество траекторий кузнечика из 0 в точку n.

Кроме того класс должен содержать скрытые методы (инкапсулированные) для вызова из метода run в зависимости от выбранного типа реализации алгоритма. [Подробнее тут](https://habr.com/ru/post/444338/).
Написать тесты для реализованного алгоритма, проверяющие весь функционал.
При реализации соблюдать [правила написания кода на Питоне](https://github.com/fefupyjava/algodspy/blob/master/README.md#%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D1%8E-%D0%BA%D0%BE%D0%B4%D0%B0).

**Comment by uselesspanda10** [comment]
Не получилось сделать наивный алгоритм перебором

**Comment by pikvic** [comment]
В алгоритме есть немного недоработок, но связаны они с тонкостями Питона. Хороший пример, чтобы разобрать на парах.
