### ISSUE TITLE
Ошибка: все функции сортировки изменяют входной список

### ISSUE THREAD

**Issue by pikvic** [fefupyjava/algodspy#46]
### Ошибка
Передаваемый список изменяется внутри функции и остаётся таким после работы функции, то есть портится. Это нежелательное поведение. Надо внимательно посмотреть и пофиксить во всех сортировках.

### Детали
Питон передаёт аргументы по ссылке (как в Си указатели), поэтому изменяемые типы изменяются внутри функции. Вот на эту тему обсуждение на [stackowerflow](https://stackoverflow.com/questions/17686596/function-changes-list-values-and-not-variable-values-in-python). А вот подробнее про функции и передачу параметров по ссылке: https://younglinux.info/python/arguments.php

**Comment by KarimIdrisov** [comment]
Стоит ли менять все сортировки? или поменять только те что делал я?

**Comment by pikvic** [comment]
> Стоит ли менять все сортировки? или поменять только те что делал я?

Если знаете, как поменять все, то меняйте, конечно! А то от остальных не дождёшься :) К тому же всё равно это будет отдельная ветка с пулл реквестом. И это и есть командная работа, что кто-то что-то сделал, другой дополнил и т.д.

**Comment by pikvic** [comment]
Нам бы и тесты потом причесать, но будем решать проблемы по мере поступления :)

**Comment by KarimIdrisov** [comment]
Можно сделать копию исходного и работать с ней уже

**Comment by KarimIdrisov** [comment]
или передать в функцию копию списка

**Comment by pikvic** [comment]
Передавать копию - плохая практика, поскольку это не user-friendly, где юзер - человек, который будет пользоваться нашим кодом. Так что да, копию внутри делать через срез или метод copy

**Comment by pikvic** [comment]
Вот прям по полочка про это: https://www.dataquest.io/blog/tutorial-functions-modify-lists-dictionaries-python/
Читать всем!
